package com.ltnc.controller;

import com.ltnc.model.Asset;
import com.ltnc.model.AssetDAO;
import org.json.JSONArray;
import org.json.JSONObject;

public class ImportAssetsController {

    private AssetDAO assetDAO;

    public ImportAssetsController() {
        this.assetDAO = new AssetDAO();
        // Ensure detail table exists on init
        this.assetDAO.ensureDetailsTableExists();
    }

    public void log(String message) {
        System.out.println("[ImportAssets JS] " + message);
    }

    // Attempt to close the window containing this webview
    public void closeWindow() {
        // Since we don't have direct stage reference injected easily,
        // we can iterate windows or pass stage in constructor?
        // Constructor is called by string classname.

        // Simpler: Use javafx.stage.Window.getWindows() filtered by title?
        // Or generic "close all modal"?

        javafx.application.Platform.runLater(() -> {
            // Hacky but works for single auxiliary window active usually
            javafx.stage.Window.getWindows().stream()
                    .filter(w -> w instanceof javafx.stage.Stage)
                    .filter(w -> "MedInventory - Import Assets".equals(((javafx.stage.Stage) w).getTitle()))
                    .findFirst()
                    .ifPresent(javafx.stage.Window::hide);
        });
    }

    // Method called from JS
    public String saveImportItems(String jsonString) {
        System.out.println("Received Import Data: " + jsonString);
        try {
            JSONObject root = new JSONObject(jsonString);
            JSONObject meta = root.getJSONObject("meta");
            JSONArray items = root.getJSONArray("items");

            String decisionNo = meta.optString("decisionNo", "");
            // String supplier = meta.optString("supplier", ""); // Log if needed later

            for (int i = 0; i < items.length(); i++) {
                JSONObject item = items.getJSONObject(i);

                String name = item.getString("name");
                String type = item.getString("type");
                int qty = item.getInt("qty");

                // Extract price properly from Item (will update JS to send it)
                double price = item.optDouble("price", 0.0);

                // Extract Vendor (Manufacturer)
                String vendor = item.optString("vendor", null); // Sent from JS

                String unit = item.optString("unit", "Cái"); // Default to Cái if missing

                // Create Asset Model
                // ID generated by DAO
                Asset asset = new Asset(
                        null,
                        name,
                        type,
                        unit,
                        qty,
                        vendor); // Set Manufacturer

                // Save/Update Asset
                assetDAO.upsertAsset(asset);

                // Process Details (if TSCD)
                if ("TSCD".equals(type)) {
                    if (item.has("details")) {
                        JSONArray details = item.getJSONArray("details");
                        for (int j = 0; j < details.length(); j++) {
                            JSONObject d = details.getJSONObject(j);
                            String serial = d.optString("serial", "");
                            String note = d.optString("note", "");
                            int manufactureYear = d.optInt("manufactureYear", 2024); // Default to current year if
                                                                                     // missing? Or 0?

                            if (!serial.isEmpty()) {
                                String itemId = assetDAO.insertFixedAssetItem(asset.getId(), serial, manufactureYear,
                                        note);
                                if (itemId != null) {
                                    // Log Transaction (IMPORT) for this specific item
                                    assetDAO.logFixedAssetTransaction(asset.getId(), itemId, "IMPORT", price,
                                            decisionNo, "Nhập mới");
                                }
                            }
                        }
                    }
                } else if ("CCDC".equals(type)) {
                    // CCDC (Tool) -> Save to TOOL table (DAO handles Dept=QTVT)
                    assetDAO.upsertTool(asset.getId(), null, qty);

                    // Log Transaction (IMPORT) for CCDC
                    assetDAO.logTransaction(asset.getId(), "IMPORT", qty, price, "Nhập mới", decisionNo);
                }

                // Log Transaction (IMPORT) -> MOVED TO INDIVIDUAL BLOCKS
                // Passing Decision No as Reason
                // Note from Item (if any specific item note, otherwise use generic)
                // For now use "Nhập mới" or item specific note if added.
                // Re-using "Nhập mới" for now.
                // assetDAO.logTransaction(asset.getId(), "IMPORT", qty, price, "Nhập mới",
                // decisionNo);
            }

            System.out.println("✓ Import saved successfully.");
            return "SUCCESS";

        } catch (Exception e) {
            e.printStackTrace();
            return "ERROR: " + e.getMessage();
        }
    }

    public String searchAssets(String query) {
        if (query == null || query.trim().isEmpty()) {
            return "[]";
        }
        java.util.List<Asset> assets = assetDAO.searchAssets(query);
        JSONArray json = new JSONArray();
        for (Asset a : assets) {
            JSONObject obj = new JSONObject();
            obj.put("name", a.getName());
            obj.put("type", a.getAsset_category());
            obj.put("unit", a.getBase_unit());
            obj.put("manufacturer", a.getManufacturer()); // Return to UI for suggestion display
            json.put(obj);

        }
        return json.toString();
    }
}
